openapi: 3.0.1
info:
  title: AI/ML NRM
  version: 18.1.0
  description: >-
    OAS 3.0.1 specification of the AI/ML NRM
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.105; AI/ML Management
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.105/
paths: {}
components:
  schemas:

#-------- Definition of types-----------------------------------------------------

    MLContext:
      type: object
      properties:
        inferenceEntityRef:
          $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'
        dataProviderRef:
          $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'

    RequestStatus:
      type: string
      enum:
        - NOT_STARTED
        - TRAINING_IN_PROGRESS
        - SUSPENDED
        - FINISHED
        - CANCELLED

    PerformanceRequirements:
      type: array
      items:
        $ref: '#/components/schemas/ModelPerformance'

    ModelPerformance:
      type: object
      properties:
        inferenceOutputName:
          type: string
        performanceMetric:
          type: string
        performanceScore:
          type: number
          format: float
        decisionConfidenceScore:
          type: number
          format: float          

    TrainingProcessMonitor:
      description: >-
        This data type is the "ProcessMonitor" data type defined in “genericNrm.yaml” with specialisations for usage in the "MLTrainingProcess".
      type: object
      properties:
        mLTrainingProcessId:
          type: string
        status:
          type: string
          enum:
            - RUNNING
            - CANCELLING
            - CANCELLED
            - SUSPENDED
            - FINSHED
        progressPercentage:
          type: integer
          minimum: 0
          maximum: 100
        progressStateInfo:
          type: string
          enum:
            - COLLECTING_DATA
            - PREPARING_TRAINING_DATA
            - TRAINING
        resultStateInfo:
          type: string

#-------- Definition of abstract IOCs --------------------------------------------



#-------- Definition of concrete IOCs --------------------------------------------

    SubNetwork-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              $ref: 'TS28623_GenericNrm.yaml#/components/schemas/SubNetwork-Attr'
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/SubNetwork-ncO'
        - type: object
          properties:
            SubNetwork:
              $ref: '#/components/schemas/SubNetwork-Multiple'
            ManagedElement:
              $ref: '#/components/schemas/ManagedElement-Multiple'
            MLTrainingFunction:
              $ref: '#/components/schemas/MLTrainingFunction-Multiple'
            MLEntityRepository:
              $ref: '#/components/schemas/MLEntityRepository-Multiple'

    ManagedElement-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              $ref: 'TS28623_GenericNrm.yaml#/components/schemas/ManagedElement-Attr'
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/ManagedElement-ncO'
        - type: object
          properties:
            MLTrainingFunction:
              $ref: '#/components/schemas/MLTrainingFunction-Multiple'
            MLEntityRepository:
              $ref: '#/components/schemas/MLEntityRepository-Multiple'

    MLTrainingFunction-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/ManagedFunction-Attr'
                - type: object
                  properties:
                    mLEntityRepositoryRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/ManagedFunction-ncO'
        - type: object
          properties:
            MLTrainingRequest:
              $ref: '#/components/schemas/MLTrainingRequest-Multiple'
            MLTrainingProcess:
              $ref: '#/components/schemas/MLTrainingProcess-Multiple'
            MLTrainingReport:
              $ref: '#/components/schemas/MLTrainingReport-Multiple'

    MLTrainingRequest-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - type: object
                  properties:
                    mLEntityId:
                      type: string
                    inferenceType:
                      type: string  
                    candidateTrainingDataSource:
                      type: array
                      items:
                        type: string
                    trainingDataQualityScore:
                      type: number
                      format: float
                    trainingRequestSource:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'
                    requestStatus:
                      $ref: '#/components/schemas/RequestStatus'
                    expectedRuntimeContext:
                      $ref: '#/components/schemas/MLContext'
                    performanceRequirements:
                      $ref: '#/components/schemas/PerformanceRequirements'
                    cancelRequest:
                      type: boolean
                    suspendRequest:
                      type: boolean
                    mLEntityToTrainRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'

    MLTrainingProcess-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - type: object
                  properties:
                    mLTrainingProcessId:
                      type: string
                    priority:
                      type: integer
                    terminationConditions:
                      type: string
                    progressStatus:
                      $ref: '#/components/schemas/TrainingProcessMonitor'
                    cancelProcess:
                      type: boolean
                    suspendProcess:
                      type: boolean
                    trainingRequestRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'
                    trainingReportRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'


    MLTrainingReport-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - type: object
                  properties:
                    mLEntityId:
                      type: string
                    areConsumerTrainingDataUsed:
                      type: boolean
                    usedConsumerTrainingData:
                      type: array
                      items:
                        type: string
                    confidenceIndication:
                      type: integer
                    modelPerformanceTraining:
                      type: array
                      items:
                        $ref: '#/components/schemas/ModelPerformance'
                    areNewTrainingDataUsed:
                      type: boolean
                    trainingRequestRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'
                    trainingProcessRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'
                    trainingReportRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'
                    lastTrainingRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'
                    mLEnityGeneratedRef:
                      $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'

    MLEntity-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                mLEntityId:
                  type: string
                inferenceType:
                  type: string
                mLEntityVersion:
                  type: string
                expectedRunTimeContext:
                  $ref: '#/components/schemas/MLContext'
                trainingContext:
                  $ref: '#/components/schemas/MLContext'
                runTimeContext:
                  $ref: '#/components/schemas/MLContext'   

    MLEntityRepository-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                mLRepositoryId:
                  type: string
            MLEntity:
              $ref: '#/components/schemas/MLEntity-Multiple'

#-------- Definition of JSON arrays for name-contained IOCs ----------------------

    SubNetwork-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/SubNetwork-Single'
    ManagedElement-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/ManagedElement-Single'
    MLTrainingFunction-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MLTrainingFunction-Single'
    MLTrainingRequest-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MLTrainingRequest-Single'
    MLTrainingProcess-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MLTrainingProcess-Single'
    MLTrainingReport-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MLTrainingReport-Single'
    MLEntity-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MLEntity-Single'
    MLEntityRepository-Multiple:
      type: array
      items:
        $ref: '#/components/schemas/MLEntityRepository-Single'

#-------- Definitions in TS 28.104 for TS 28.532 ---------------------------------

    resources-AiMlNrm:
      oneOf:
        - $ref: '#/components/schemas/SubNetwork-Single'
        - $ref: '#/components/schemas/ManagedElement-Single'

        - $ref: '#/components/schemas/MLTrainingFunction-Single'
        - $ref: '#/components/schemas/MLTrainingRequest-Single'
        - $ref: '#/components/schemas/MLTrainingProcess-Single'
        - $ref: '#/components/schemas/MLTrainingReport-Single'
        - $ref: '#/components/schemas/MLEntity-Single'
        - $ref: '#/components/schemas/MLEntityRepository-Single'
