openapi: 3.0.0

info:
  title: EES ACR Parameters Information Service
  version: 1.0.0-alpha.2
  description: |
    EES ACR Parameters Information Service.  
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: >
    3GPP TS 29.558 V18.3.0; Enabling Edge Applications;
    Application Programming Interface (API) specification; Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.558/

security:
  - {}
  - oAuth2ClientCredentials: []

servers:
  - url: '{apiRoot}/eees-acr-param/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122

paths:
  /send-acrparamsinfo:
    post:
      summary: Request to send ACR parameters information.
      operationId: Request
      tags:
        - Send ACR Parameter Information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ACRParamsInfo'
      responses:
        '200':
          description: >
            The ACR parameters information is successfully received and the content of these ACR
            parameters information is returned in the response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ACRParamsInfo'
        '204':
          description: >
            No Content. The ACR parameter information is successfully received and no content is
            returned in the response body.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

components:

  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}

  schemas:
    ACRParamsInfo:
      description: >
        Represents the ACR parameters information.
      type: object
      properties:
        eesId:
          type: string
          description: Represents the EES ID.
        eecId:
          type: string
          description: Represents the EEC ID.
        acId:
          type: string
          description: Represents the AC ID.
        sEasEndPoint:
          $ref: 'TS29558_Eees_EASRegistration.yaml#/components/schemas/EndPoint'
        tEasEndPoint:
          $ref: 'TS29558_Eees_EASRegistration.yaml#/components/schemas/EndPoint'
        acrParams:
          $ref: 'TS29558_Eees_ACRManagementEvent.yaml#/components/schemas/ACRParameters'
      required:
        - eesId
        - eecId
        - acId
        - sEasEndPoint
        - tEasEndPoint
        - acrParams
